apiVersion: v1
kind: Service
metadata:
  name: counter-database
  labels:
    app: counter-database
spec:
  selector:
    app: counter-database
    tier: database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
 