apiVersion: v1
kind: Secret
metadata:
  name: counter-database
  namespace: default
  labels:
    app: counter-app
type: Opaque
stringData:
  database-host: Rafaelhost
  database-name: rafaelDB
  database-user: rafael
  database-password: stern123